### ISSUE TITLE
[Feater Request] Add fill and stroke parameter

### ISSUE THREAD

**Issue by FrazeColder** [vaetas/feather_icons_svg#1]
Hey @vaetas 
thanks for that fantastic package which allows me to pass the `stroke-width` to the icon as well. I just took a look at the FeaterIcon class and am I wondering if it is possible to extend the parameters. 

It wold be very nice if we could also pass the `fill` and the `stroke` parameter to the class. Do you think you can add this feature?

Kind regards

**Comment by vaetas** [comment]
Hello,
*stroke width* seems to be the only customizable property of Feather Icons judging by their website. Changing *fill* color would probably cause undefined glitches in the icons. Because of this I would prefer not to allow changing them within the constructor. 

As for *stroke* color, this does not have any effect. You can change the color of your icon using the `color` param in `FeatherIcon` constructor. I hardcode the color to `#000000` only because when I created this package the `flutter_svg` did not support `currentColor` value. Also, `FeatherIcon` will respect your current `IconTheme` if you do not provide `color` param.

If you need your icons more customized I suggest you to edit the raw SVG.

I would be happy to hear any further arguments. Otherwise I will close this issue.

Thanks.

**Comment by FrazeColder** [comment]
Hey @vaetas 
this here is the offical linked answer by the team behind Feather Icon: https://github.com/feathericons/feather/issues/225#issuecomment-345473232

They basically say they will not support filled (solid) icons but theyself say you can change this by changing the `fill` attribute as the icon is in svg. I already tried this and it works without any problems. So, I don't see any problems here. Are we able to add that feature?

Thanks

**Comment by vaetas** [comment]
I understand your point but only few icons make sense with fill color. I want to avoid situation where people try to use `fill` value and then achieve faulty icons.

I certainly need to give this problem some thoughts. Therefore I cannot give any ETA. Still, I lean towards not supporting this feature at all. I am not sure I would use something like this and if I want to support further development for this feature.

If you need this feature right now I suggest you copy the SVG and customize it yourself by hand for the icons you need. If you want all icons to be filled I still believe it would be better to find different icon set and skip Feather Icons.

**Comment by FrazeColder** [comment]
@vaetas thanks mate! I thinkn I will just fork you project then. I just need a couple of icons to be filled like a star or a bookmark icon when something is saved.
